### ISSUE TITLE
FUN 10.5 

### ISSUE THREAD

**Issue by AmelMammar** [foselab/abz2024_casestudy_MLV#1]
Dear all,
Perhaps, FUN 10.5 needs to be more precise because according to the figure 2, the following scenario is possible: 
1. The system is in the ventilation mode 
2. Stop ventilation while the patient is still connected: the system becomes in StandBy mode
3. It is possible to proceed with alarm testing : FUN 10.5 is violated

Best regads,
Amel Mammar

**Comment by silviabonfanti** [comment]
We have decided to remove the alarm test mode since going into details would complicate the specification
