### ISSUE TITLE
Error on the controller

### ISSUE THREAD

**Issue by AmelMammar** [foselab/abz2024_casestudy_MLV#10]
How does an error, on the controler, affect/impact the GUI? There is a transition labelled "error" on Figure 4.1, but we do bot know how it is propagated on the GUI (Figure 3.1).

**Comment by garganti** [comment]
We have added a new requirement (AL38.1): in case of a failure of the controller, the GUI raises a visual alarm. Probably after a short time, all the data about pressure and flow will be wrong.
