### ISSUE TITLE
Values of max_exp_pause and max_ins_pause

### ISSUE THREAD

**Issue by AmelMammar** [foselab/abz2024_casestudy_MLV#13]
Unless I'm mistaken, I did not see default/rang values for max_exp_pause and max_ins_pause.

**Comment by silviabonfanti** [comment]
The values are in FUN.28 and FUN.29, and repeated in GUI.58 and GUI.59

**Comment by AmelMammar** [comment]
As the requirement document is long, I think it would be better to use explicitly the constants max_exp_pause and min_exp_pause.
