### ISSUE TITLE
Target inspiratory pressure Pinsp

### ISSUE THREAD

**Issue by AmelMammar** [foselab/abz2024_casestudy_MLV#15]
Why is Target inspiratory pressure (P_insp) not considered as common parameter for PSV and PVS?-

**Comment by AmelMammar** [comment]
Same question for ITS.  Why do we have ITS and ITS_psv?

**Comment by silviabonfanti** [comment]
This is a medical choice, because physician could choose different values based on patient condition and ventilation mode.
