### ISSUE TITLE
FUN4 and FUN 10.5

### ISSUE THREAD

**Issue by garganti** [foselab/abz2024_casestudy_MLV#2]
FUN.4 still makes reference to Alarm mode.
Moreover, is it possible to set ventilation parameters while having the patient connected. According to FUN10.5, this is forbidden. But Figure 2 allows that.
(by Amel Mammar)

**Comment by silviabonfanti** [comment]
We have removed reference to Alarm mode in FUN.4
Regarding the second point: it's possible to set ventilation parameters while having the patient connected. 
FUN.10.5 says that it should be possible to set ventilation and alarm parameters ALSO before connecting the patient.
This doesn't exclude that parameters can be set also when the ventilator is ventilating a patient.
