### ISSUE TITLE
Relationship between a requirement and sub-requirements

### ISSUE THREAD

**Issue by mluckcuck** [foselab/abz2024_casestudy_MLV#6]
In several places, requirements have sub-requirements (e.g. FUN.5 then has FUN.5.1 -- FUN.5.3) that seem to add detail/support the 'main' requirement. In other places, however, (e.g. FUN.4) there is a lot of detail contained in one requirement.

I was wondering, in general, what your view of the relationship is between a requirement and its sub-requirements. For example, are they extra clauses in addition to the main requirement? Do the sub-requirements combine to 'implement' what the main requirement says? Or is it something else?

Thanks

**Comment by garganti** [comment]
The requirements in chapter 1 are general requirements, then they are detailed in the following chapters of the document.
Generally, the sub requirements detail the content of the general requirement by specifying the behavior.

**Comment by garganti** [comment]
@mluckcuck please close the issue if the answer is satisfactory.

**Comment by mluckcuck** [comment]
Hi Again,

> "Generally, the sub requirements detail the content of the general requirement by specifying the behavior."

So can I think of, e.g., FUN5 as being defined as FUN5.1 and FUN5.2 and FUN5.3; or does that not work?

**Comment by silviabonfanti** [comment]
In this case, FUN.5 specifies how start-up is initiated (by pushing the power button), and the sub requirements specifies what happens during the initialization process (e.g. during initialization the system loads default parameters - FUN.5.1).

**Comment by mluckcuck** [comment]
> In this case, FUN.5 specifies how start-up is initiated (by pushing the power button), and the sub requirements specifies what happens during the initialization process (e.g. during initialization the system loads default parameters - FUN.5.1).

Ah, so they are extra clauses of the main requirement? So it's, for example, FUN 5 plus all of its sub-requirements?

**Comment by silviabonfanti** [comment]
Yes, that's right!

**Comment by mluckcuck** [comment]
Great. Thanks for your explanation, this is much more clear now.
