### ISSUE TITLE
Labelling states machines with same labels

### ISSUE THREAD

**Issue by AmelMammar** [foselab/abz2024_casestudy_MLV#8]
As states machines have common states, I think it would be better to have same labels on the equivalent transitions/states. 
For instance, Does the condition "Ventilating", in Figure 3.1, mean "new patient" ? If so, we can replace the label Yes by "start Ventilation"? 
In other words, it is not possible to have Figure 4.1 in State PSV/PCV and Figure 3.1 in State "Ventilating". Am I right?

**Comment by silviabonfanti** [comment]
We have updated Fig 3.1, here is the new version:

<img width="812" alt="image" src="https://github.com/foselab/abz2024_casestudy_MLV/assets/8759501/f1d3cbcf-a334-404c-bb71-d472675b8d26">

Moreover, we have updated GUI.4 and added GUI.108,109,110:

GUI.4
The transition from Start to Self Test shall occur if the user wants to test the machine and set the proper parameters for a new patient. 
Rationale: the clinician decides to check the status of the machine sensors before starting ventilation.

GUI.108
The transition from Ventilation to Settings shall occur if the operator wants to adjust ventilation settings.

GUI.109
The transition from Settings to Ventilation shall occur if the ventilator is ventilating and the operator has finished setting the parameters.

GUI.110
The transition from Settings to Menu shall occur if the ventilation is off and the operator has finished setting the parameters.

Hope this answer to your issue.
In case, please close this issue.

**Comment by AmelMammar** [comment]
The updates clarify some points but do not answer my issue. Could you give a precise answer to each point: 

1. As states machines (Figures 2.1, 3.1 and 4.1) have common states, I think it would be better to have same labels on the equivalent transitions/states.
For instance, does the condition "Ventilating", in Figure 3.1, mean "new patient"  as that of Figure 2.1 ? If so, we can replace the label Yes by "start Ventilation"?
2. In other words, it is not possible to have Figure 4.1 in State PSV/PCV and Figure 3.1 in State "StartUp". Am I right?

**Comment by garganti** [comment]
1. Regarding common states, please keep in mind that Figure 2.1 reports a global view, while Fig. 3.1 and 4.1 refer to components. So mapping is not always 1 to 1. In particular, the GUI could become out of sync with the controller. We tried to map states of Fig. 2.1 with the states of the components GUI and Controller in this way (normally when the components are in sync):

|  Fig. 2.1 System | Fig. 3.1 GUI      | Fig. 4.1 Controller |
|--------------  |-----------------|------------------|
| Start-up         | Start-up           | Start-up            |
| new patient?| Start (*)                 | N/A                   |
| SelfTest         | SelfTest           | SelfTest (**)              |
| StandBy        | Menu/Settings         | VentilationOff | 
| Ventilation    | Ventilation/Settings | PCV/PSV         |
| FailSafe         | (Menu)                     | FailSafe         |

(*) the GUI in the start menu asks if the operator wants to resume ventilation or start with a new patient
(**) the controller makes the self test only once, it cannot be re entered. 

2. It is possible to have the components not all in the same states. In case the GUI crashes, it restarts from star-up while the controller is still working (in PCV or PSV).  

We have changed some names in the state machines and published a new version (1.3) at this point.

**Comment by AmelMammar** [comment]
Thank you very much for these clarifications.

**Comment by AmelMammar** [comment]
Thank you very much for these clarifications.

**Comment by AmelMammar** [comment]
1. Is it possible to run self test while the controller is in the state VentilationOff? I mean a second test after stopping the current ventilation. If no, the transition runSelfTest should have a guard. 
2. In a normal case, does start-up-ended of the controller occur before that of the GUI? 
3. In a nomal case, I think the state SelfTest of the controller includes both the states Start and  SelfTest  of the GUI. Is it OK ?
4. In a nomal case, can GUI be faster than the controller? Can GUI be in  the state Start before the controller was in the state SelfTest.

**Comment by garganti** [comment]
1. working on it
2. yes, it can happen - actually the controller is normally faster than the GUI, so it is likely to happen
3. not clear the meaning of _includes_ .
4. yes it can happen.

**Comment by AmelMammar** [comment]
For the point 3, I think that when the controller is in the state SelfTest , the GUI may be either in the state Start or SelfTest  or even in the state StartUp.

**Comment by silviabonfanti** [comment]
That's correct. Being in Start or StartUp is temporary.
